export const footballEn = {
  id: 2856,
  slug: 'football',
  slugs: { it: 'italian-football', hr: 'nogometna-lopta', en: 'football' },
  sectionId: 59,
  languageId: 'en',
  isPublished: true,
  publishedFrom: '2021-01-21T08:58:00',
  publishedTo: null,
  category: { id: 2854, slug: 'sport', name: 'sport', itemCount: null },
  data: {
    author: 'Karlo M',
    title: 'Football',
    description: 'A beautiful ball',
    text: '<p>Go out and play football. </p>',
    whatIsIt: 'sports item',
    modelNumber: '3',
    recommended: false,
  },
  seoMetadata: '[]',
  image: null,
  images: [],
  contents: null,
  connectionStats: null,
  connections: {},
  event: null,
  collectionItems: null,
  subsections: null,
};
